parse_config:
  modifier_fn_map:
    left_shift: ⇧
    left_alt: ⌥
    right_alt: Alt
    left_ctrl: ^
    left_gui: ⌘
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

  raw_binding_map:
    "&bt_sel 0": BT 1
    "&bt_sel 1": BT 2
    "&bt_sel 2": BT 3
    "&bt_sel 3": BT 4
    "&bt_sel 4": BT 5
    "&bt_clr 0": clear 1
    "&bt_clr 1": clear 2
    "&bt_clr 2": clear 3
    "&bt_clr 3": clear 4
    "&bt_clr 4": clear 5
    "&caps_word": caps word
    "&flash 8": flash
    "&ind_bat": battery status
    "&ind_con": connection status
    "&mkp LCLK": "mouse click"
    "&mkp RCLK": "right click"
    "&mmv MOVE_DOWN": mouse ↓
    "&mmv MOVE_LEFT": mouse ←
    "&mmv MOVE_RIGHT": mouse →
    "&mmv MOVE_UP": mouse ↑
    "&mouse_pair": pair mouse
    "&msc SCRL_DOWN": scroll ↓
    "&msc SCRL_LEFT": scroll ←
    "&msc SCRL_RIGHT": scroll →
    "&msc SCRL_UP": scroll ↑
    "&sk LSHIFT": sticky ⇧
    "&studio_unlock": ZMK Studio
    "&tmux A": rename
    "&tmux C": new
    "&tmux D": detach
    "&tmux N": tab →
    "&tmux N1": tab 1
    "&tmux N2": tab 2
    "&tmux N3": tab 3
    "&tmux N4": tab 4
    "&tmux N5": tab 5
    "&tmux N6": tab 6
    "&tmux N7": tab 7
    "&tmux N8": tab 8
    "&tmux N9": tab 9
    "&tmux P": ← tab
    "&tmux QMARK": help
    "&usb_sel": USB
    "&vim N1": tab 1
    "&vim N2": tab 2
    "&vim N3": tab 3
    "&vim N4": tab 4
    "&vim N5": tab 5
    "&vim N6": tab 6
    "&vim N7": tab 7
    "&vim N8": tab 8
    "&vim N9": tab 9
    "&vim Q": exit
    "&vim W": save
    "&vimQ": QUIT!
    "&vtabnxt": tab →
    "&vtabprv": ← tab

    GC(Q): lock screen
    GCS(N4): screen copy
    GS(LBKT): ← tab
    GS(RBKT): tab →
    GS(N4): screen shot
    HYPR(N4): launch pad

  zmk_keycode_map:
    AMPS: "&"
    AT: "@"
    BACKSLASH: \
    BSLH: \
    BSPC: ⌫
    CAPS: Caps 🔒
    CARET: ^
    COLON: ":"
    COMMA: ","
    C_NEXT: ⏭
    C_PP: ⏯
    C_PREV: ⏮
    DEL: ⌦
    DLLR: $
    DOT: .
    DOWN: ↓
    END: End
    EQUAL: "="
    ESC: Esc
    EXCL: "!"
    GLOBE: 🌐
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    HOME: Home
    KP_NUM: Num 🔒
    LALT: ⌥
    LBKT: "["
    LBRC: "{"
    LCTL: ^
    LCTRL: ^
    LC(UP): mission control
    LEFT: ←
    LGUI: ⌘
    LPAR: (
    LSHFT: ⇧
    LSHIFT: sticky shift
    LT: <
    MINUS: "-"
    PG_DN: PgDn
    PG_UP: PgUp
    PIPE: "|"
    PLUS: +
    PRCNT: "%"
    QMARK: "?"
    RALT: Alt
    RBKT: "]"
    RBRC: "}"
    RET: ↵
    RIGHT: →
    RPAR: )
    SEMI: ;
    SLASH: /
    SPC: ␣
    SQT: "'"
    STAR: "*"
    TAB: ⇥
    TILDE: "~"
    UNDER: _
    UP: ↑

  zmk_combos:
    combo_unlock:
      align: top
      offset: 1
    combo_b:
      dendron: true
    combo_j:
      dendron: true
    combo_less_than:
      dendron: true
    combo_greater_than:
      dendron: true
    combo_esc:
      draw_separate: true
    combo_tab:
      draw_separate: true
    combo_backspace:
      draw_separate: true
    combo_return:
      draw_separate: true
    combo_mouse_click:
      layers: [flash mode]
    combo_mouse_right_click:
      layers: [flash mode]
    combo_mouse_up:
      layers: [flash mode]
    combo_mouse_down:
      layers: [flash mode]
    combo_mouse_left:
      layers: [flash mode]
    combo_mouse_right:
      layers: [flash mode]
    combo_scroll_up:
      layers: [flash mode]
    combo_scroll_down:
      layers: [flash mode]
    combo_scroll_left:
      layers: [flash mode]
    combo_scroll_right:
      layers: [flash mode]
    combo_flash:
      dendron: true
